# Generated by Django 4.2.7 on 2025-03-31 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("userauths", "0004_alter_user_otp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="token",
            field=models.CharField(blank=True, max_length=5000, null=True),
        ),
    ]
